




(function (ND) {
  'use strict';
  const LANGS = ['tr', 'es', 'pt', 'ru', 'de', 'fr', 'it', 'pl', 'id', 'vi', 'th', 'hi', 'ar', 'zh', 'zh-TW', 'ja', 'ko'];
  const T = {

    'DISARMED!': ['SİLAHSIZ!', '¡DESARMADO!', 'DESARMADO!', 'ОБЕЗОРУЖЕН!', 'ENTWAFFNET!', 'DÉSARMÉ !', 'DISARMATO!', 'ROZBROJONY!', 'TERLUCUTI!', 'MẤT KIẾM!', 'ปลดอาวุธ!', 'निहत्था!', 'جُرِّد!', '缴械！', '繳械！', '武器落とし！', '무장 해제!'],
    'SWORD BACK!': ['KILIÇ GERİ!', '¡ESPADA DE VUELTA!', 'ESPADA DE VOLTA!', 'МЕЧ В РУКЕ!', 'SCHWERT ZURÜCK!', 'ÉPÉE REPRISE !', 'SPADA RIPRESA!', 'MIECZ ODZYSKANY!', 'PEDANG KEMBALI!', 'LẤY LẠI KIẾM!', 'ได้ดาบคืน!', 'तलवार वापस!', 'استعاد السيف!', '夺回刀！', '奪回刀！', '刀を取り戻した！', '검 회수!'],
    'CATCH!': ['YAKALADI!', '¡ATRAPADO!', 'AGARROU!', 'ПЕРЕХВАТ!', 'GEFANGEN!', 'SAISI !', 'PRESO!', 'CHWYT!', 'TANGKAP!', 'BẮT ĐƯỢC!', 'จับได้!', 'पकड़ा!', 'إمساك!', '擒住！', '擒住！', 'つかんだ！', '잡았다!'],
    'KICKED AWAY!': ['TEKMEYLE UZAKTA!', '¡LEJOS DE UNA PATADA!', 'CHUTADA PARA LONGE!', 'ОТБРОШЕН ПИНКОМ!', 'WEGGETRETEN!', 'ÉCARTÉE !', 'CALCIATA VIA!', 'ODKOPNIĘTY!', 'DITENDANG JAUH!', 'ĐÁ VĂNG!', 'เตะกระเด็น!', 'लात से दूर!', 'رُكلت بعيدًا!', '踢飞！', '踢飛！', '蹴り飛ばした！', '걷어찼다!'],
    'OFF-LINE!': ['YANLIŞ TARAF!', '¡FUERA DE LÍNEA!', 'FORA DE LINHA!', 'МИМО ЛИНИИ!', 'FALSCHE SEITE!', 'MAUVAIS CÔTÉ !', 'FUORI LINEA!', 'ZŁA STRONA!', 'SALAH SISI!', 'LỆCH HƯỚNG!', 'ผิดทาง!', 'गलत तरफ़!', 'الجهة الخطأ!', '偏位！', '偏位！', 'ずれた！', '빗나간 방어!'],
    'PINNED!': ['SAPLANDI!', '¡INMOVILIZADO!', 'IMOBILIZADO!', 'ПРИЖАТ!', 'FESTGENAGELT!', 'CLOUÉ !', 'INCHIODATO!', 'PRZYGWOŻDŻONY!', 'TERJEPIT!', 'BỊ GHIM!', 'ถูกตรึง!', 'जकड़ा!', 'مُثبَّت!', '钉住！', '釘住！', '釘付け！', '고정!'],
    'PUNISHED!': ['CEZALANDIRDI!', '¡CASTIGADO!', 'PUNIDO!', 'НАКАЗАН!', 'BESTRAFT!', 'PUNI !', 'PUNITO!', 'UKARANY!', 'DIHUKUM!', 'BỊ TRỪNG PHẠT!', 'โดนลงโทษ!', 'सज़ा!', 'عوقب!', '惩罚！', '懲罰！', '咎めた！', '응징!'],
    'DUCK!': ['EĞİL!', '¡AGÁCHATE!', 'ABAIXA!', 'ПРИГНИСЬ!', 'DUCKEN!', 'BAISSE-TOI !', 'ABBASSATI!', 'UNIK!', 'MERUNDUK!', 'CÚI!', 'ก้ม!', 'झुको!', 'انحنِ!', '下蹲！', '下蹲！', 'かがめ！', '숙여!'],
    'SWAY!': ['GERİL!', '¡ESQUIVA!', 'DESVIA!', 'УКЛОН!', 'AUSWEICHEN!', 'ESQUIVE !', 'SCHIVA!', 'ODCHYLENIE!', 'MENGELAK!', 'NGẢ NGƯỜI!', 'เอนหลบ!', 'पीछे झुको!', 'تمايل!', '闪身！', '閃身！', 'スウェー！', '스웨이!'],
    'SLIP!': ['SIYRIL!', '¡ESCAPA!', 'ESCAPA!', 'УВОРОТ!', 'WEGTAUCHEN!', 'ESQUIVE BASSE !', 'SCANSA!', 'UNIK NÓG!', 'MENGHINDAR!', 'NHẢY TRÁNH!', 'ยกขาหลบ!', 'बच निकलो!', 'تفادٍ!', '提腿！', '提腿！', 'かわした！', '피했다!'],
    'RE-ARMED': ['YENİDEN SİLAHLI', 'REARMADO', 'REARMADO', 'СНОВА С МЕЧОМ', 'WIEDER BEWAFFNET', 'RÉARMÉ', 'RIARMATO', 'ZNÓW Z MIECZEM', 'BERSENJATA LAGI', 'CÓ KIẾM LẠI', 'มีอาวุธอีกครั้ง', 'फिर हथियारबंद', 'مسلح من جديد', '重新持刀', '重新持刀', '再武装', '재무장'],
    'BIND READY': ['KİLİT HAZIR', 'TRABA LISTA', 'TRAVA PRONTA', 'ЗАХВАТ ГОТОВ', 'BINDUNG BEREIT', 'LIAGE PRÊT', 'LEGATURA PRONTA', 'ZWARCIE GOTOWE', 'KUNCI SIAP', 'SẴN SÀNG KHÓA', 'ล็อกดาบพร้อม', 'बंधन तैयार', 'القفل جاهز', '绞刀就绪', '絞刀就緒', 'バインド準備', '바인드 준비'],
    'BOUND!': ['KİLİTLENDİ!', '¡TRABADO!', 'TRAVADO!', 'ЗАХВАЧЕН!', 'GEBUNDEN!', 'LIÉ !', 'LEGATO!', 'ZWARTY!', 'TERKUNCI!', 'BỊ KHÓA!', 'ถูกล็อก!', 'बंधा!', 'مقفول!', '被绞住！', '被絞住！', 'バインド！', '묶였다!'],
    'STRIKE!': ['VUR!', '¡GOLPEA!', 'GOLPEIA!', 'БЕЙ!', 'SCHLAG ZU!', 'FRAPPE !', 'COLPISCI!', 'UDERZ!', 'SERANG!', 'ĐÁNH!', 'ฟัน!', 'वार करो!', 'اضرب!', '出手！', '出手！', '打て！', '쳐라!'],
    'UNARMED': ['SİLAHSIZ', 'DESARMADO', 'DESARMADO', 'БЕЗ ОРУЖИЯ', 'UNBEWAFFNET', 'DÉSARMÉ', 'DISARMATO', 'BEZ BRONI', 'TANPA SENJATA', 'TAY KHÔNG', 'มือเปล่า', 'निहत्था', 'أعزل', '空手', '空手', '素手', '맨손'],
    'PICK UP': ['AL', 'RECOGER', 'PEGAR', 'ПОДНЯТЬ', 'AUFHEBEN', 'RAMASSER', 'RACCOGLI', 'PODNIEŚ', 'AMBIL', 'NHẶT', 'เก็บ', 'उठाओ', 'التقط', '拾起', '拾起', '拾う', '줍기'],
    'BLOCK': ['BLOK', 'BLOQUEO', 'BLOQUEIO', 'БЛОК', 'BLOCK', 'BLOCAGE', 'PARATA', 'BLOK', 'TANGKIS', 'ĐỠ', 'ป้องกัน', 'ब्लॉक', 'صد', '格挡', '格擋', 'ブロック', '막기'],
    'CUT!': ['KESİK!', '¡CORTE!', 'CORTE!', 'РАЗРУБ!', 'SCHNITT!', 'TRANCHÉ !', 'TAGLIO!', 'CIĘCIE!', 'TEBAS!', 'CHÉM!', 'ฟันขาด!', 'कटा!', 'قطع!', '斩！', '斬！', '斬った！', '베기!'],
    'Guard now to escape!': ['Kurtulmak için şimdi savun!', '¡Defiende ahora para escapar!', 'Defenda agora para escapar!', 'Защищайся сейчас, чтобы вырваться!', 'Jetzt blocken, um zu entkommen!', 'Garde maintenant pour t’échapper !', 'Para ora per sfuggire!', 'Broń się teraz, by uciec!', 'Tangkis sekarang untuk lolos!', 'Đỡ ngay để thoát!', 'ป้องกันตอนนี้เพื่อหนี!', 'बचने के लिए अभी बचाव करो!', 'دافع الآن لتفلت!', '现在防御即可脱身！', '現在防禦即可脫身！', '今ガードで脱出！', '지금 막아서 빠져나가!'],
    'ESCAPED': ['KAÇTI', 'ESCAPÓ', 'ESCAPOU', 'ВЫРВАЛСЯ', 'ENTKOMMEN', 'ÉCHAPPÉ', 'SCAMPATO', 'UCIEKŁ', 'LOLOS', 'THOÁT', 'หลุดรอด', 'बच निकला', 'أفلت', '挣脱', '掙脫', '逃れた', '빠져나감'],
    'MISSED · BROKEN': ['KAÇIRDI · KIRILDI', 'FALLÓ · ROTO', 'ERROU · QUEBRADO', 'МИМО · СЛОМЛЕН', 'VERPASST · GEBROCHEN', 'RATÉ · BRISÉ', 'MANCATO · ROTTO', 'CHYBIENIE · ZŁAMANY', 'MELESET · PATAH', 'TRƯỢT · VỠ THẾ', 'พลาด · เสียท่า', 'चूका · टूटा', 'أخطأ · انكسر', '落空 · 破势', '落空 · 破勢', '外した · 崩れた', '실패 · 무너짐'],
    'TOO EARLY · BROKEN': ['ERKEN · KIRILDI', 'DEMASIADO PRONTO · ROTO', 'CEDO DEMAIS · QUEBRADO', 'РАНО · СЛОМЛЕН', 'ZU FRÜH · GEBROCHEN', 'TROP TÔT · BRISÉ', 'TROPPO PRESTO · ROTTO', 'ZA WCZEŚNIE · ZŁAMANY', 'TERLALU CEPAT · PATAH', 'QUÁ SỚM · VỠ THẾ', 'เร็วไป · เสียท่า', 'जल्दी · टूटा', 'مبكر جدًا · انكسر', '太早 · 破势', '太早 · 破勢', '早すぎ · 崩れた', '너무 빠름 · 무너짐'],
    'TOO EARLY · ESCAPED': ['ERKEN · KAÇTI', 'DEMASIADO PRONTO · ESCAPÓ', 'CEDO DEMAIS · ESCAPOU', 'РАНО · ВЫРВАЛСЯ', 'ZU FRÜH · ENTKOMMEN', 'TROP TÔT · ÉCHAPPÉ', 'TROPPO PRESTO · SCAMPATO', 'ZA WCZEŚNIE · UCIEKŁ', 'TERLALU CEPAT · LOLOS', 'QUÁ SỚM · THOÁT', 'เร็วไป · หลุดรอด', 'जल्दी · बच निकला', 'مبكر جدًا · أفلت', '太早 · 挣脱', '太早 · 掙脫', '早すぎ · 逃れた', '너무 빠름 · 빠져나감'],
    'SMASH!': ['KIRDI!', '¡ZAS!', 'PÁ!', 'ВДРЕБЕЗГИ!', 'ZERSCHMETTERT!', 'FRACAS !', 'SCHIANTO!', 'ROZBITE!', 'HANCUR!', 'VỠ TAN!', 'แตกกระจาย!', 'चकनाचूर!', 'تحطم!', '砸碎！', '砸碎！', '粉砕！', '박살!'],
    'WHAM!': ['GÜM!', '¡PUM!', 'PUM!', 'БАХ!', 'WUMMS!', 'BAM !', 'BAM!', 'BUM!', 'BUK!', 'RẦM!', 'ปัง!', 'धड़ाम!', 'طاخ!', '砰！', '砰！', 'ドカン！', '쾅!'],
    'TABLE FLIP!': ['MASA DEVRİLDİ!', '¡MESA VOLCADA!', 'MESA VIRADA!', 'СТОЛ ОПРОКИНУТ!', 'TISCH UMGEWORFEN!', 'TABLE RENVERSÉE !', 'TAVOLO RIBALTATO!', 'STÓŁ PRZEWRÓCONY!', 'MEJA TERBALIK!', 'LẬT BÀN!', 'พลิกโต๊ะ!', 'मेज़ पलटी!', 'قلب الطاولة!', '掀桌！', '掀桌！', 'ちゃぶ台返し！', '테이블 뒤집기!'],
    'OFF THE VERANDA!': ['VERANDADAN AŞAĞI!', '¡FUERA DE LA TERRAZA!', 'PARA FORA DA VARANDA!', 'С ВЕРАНДЫ!', 'VON DER VERANDA!', 'HORS DE LA VÉRANDA !', 'GIÙ DALLA VERANDA!', 'Z WERANDY!', 'JATUH DARI BERANDA!', 'RƠI KHỎI HIÊN!', 'ตกระเบียง!', 'बरामदे से नीचे!', 'من الشرفة!', '跌下回廊！', '跌下迴廊！', '縁側から落ちた！', '툇마루 밖으로!'],
    'STUCK IN THE POST!': ['DİREĞE SAPLANDI!', '¡CLAVADA EN EL POSTE!', 'PRESA NO POSTE!', 'ЗАСТРЯЛ В СТОЛБЕ!', 'IM PFOSTEN STECKEN!', 'COINCÉE DANS LE POTEAU !', 'INCASTRATA NEL PALO!', 'UTKWIŁ W SŁUPIE!', 'TERTANCAP DI TIANG!', 'KẸT VÀO CỘT!', 'ติดเสา!', 'खंभे में फँसा!', 'علق في العمود!', '卡进柱子！', '卡進柱子！', '柱に刺さった！', '기둥에 박혔다!'],
    'THROUGH THE SHOP FRONT!': ['DÜKKÂNIN İÇİNDEN!', '¡A TRAVÉS DEL ESCAPARATE!', 'ATRAVÉS DA VITRINE!', 'СКВОЗЬ ЛАВКУ!', 'DURCH DEN LADEN!', 'À TRAVERS LA BOUTIQUE !', 'ATTRAVERSO LA BOTTEGA!', 'PRZEZ SKLEP!', 'MENEMBUS TOKO!', 'XUYÊN QUA CỬA HÀNG!', 'ทะลุหน้าร้าน!', 'दुकान के आर-पार!', 'عبر واجهة المتجر!', '撞穿店面！', '撞穿店面！', '店先を突き破った！', '가게를 뚫고!'],
    'THROUGH THE STALL!': ['TEZGÂHIN İÇİNDEN!', '¡A TRAVÉS DEL PUESTO!', 'ATRAVÉS DA BANCA!', 'СКВОЗЬ ПРИЛАВОК!', 'DURCH DEN STAND!', 'À TRAVERS L\'ÉTAL !', 'ATTRAVERSO LA BANCARELLA!', 'PRZEZ STRAGAN!', 'MENEMBUS LAPAK!', 'XUYÊN QUA SẠP!', 'ทะลุแผงลอย!', 'ठेले के आर-पार!', 'عبر الكشك!', '撞穿摊位！', '撞穿攤位！', '屋台を突き破った！', '노점을 뚫고!'],
    'DRAW!': ['ÇEK!', '¡DESENVAINA!', 'SAQUE!', 'ВЫХВАТЫВАЙ!', 'ZIEH!', 'DÉGAINE !', 'SGUAINA!', 'DOBĄDŹ!', 'CABUT!', 'RÚT KIẾM!', 'ชักดาบ!', 'निकालो!', 'استلّ!', '拔刀！', '拔刀！', '抜け！', '뽑아라!'],
    'KICK!': ['TEKME!', '¡PATADA!', 'CHUTE!', 'ПИНОК!', 'TRITT!', 'COUP DE PIED !', 'CALCIO!', 'KOPNIĘCIE!', 'TENDANG!', 'ĐÁ!', 'เตะ!', 'लात!', 'ركلة!', '踢！', '踢！', '蹴り！', '발차기!'],
    'PULL!': ['ÇEK!', '¡TIRA!', 'PUXA!', 'ТЯНИ!', 'ZIEH!', 'TIRE !', 'TIRA!', 'CIĄGNIJ!', 'TARIK!', 'KÉO!', 'ดึง!', 'खींचो!', 'اسحب!', '拉！', '拉！', '引け！', '당겨!'],
    'STOOL!': ['TABURE!', '¡TABURETE!', 'BANQUINHO!', 'ТАБУРЕТ!', 'HOCKER!', 'TABOURET !', 'SGABELLO!', 'TABORET!', 'BANGKU!', 'GHẾ ĐẨU!', 'ม้านั่ง!', 'स्टूल!', 'مقعد!', '凳子！', '凳子！', '腰掛け！', '의자!'],
    'SWEEP!': ['SÜPÜR!', '¡BARRIDO!', 'RASTEIRA!', 'ПОДСЕЧКА!', 'FEGER!', 'BALAYAGE !', 'SPAZZATA!', 'PODCIĘCIE!', 'SAPU!', 'QUÉT CHÂN!', 'กวาดขา!', 'टंगड़ी!', 'كنس!', '扫腿！', '掃腿！', '足払い！', '다리 걸기!'],
    'TWIST!': ['BÜK!', '¡GIRA!', 'TORCE!', 'ВЫКРУТ!', 'DREH!', 'TORSION !', 'TORCI!', 'SKRĘT!', 'PUTAR!', 'VẶN!', 'บิด!', 'मरोड़ो!', 'لفّ!', '拧！', '擰！', 'ひねれ！', '비틀어!'],
    'VAULT!': ['ATLA!', '¡SALTA!', 'SALTA!', 'ПРЫЖОК!', 'SPRUNG!', 'SAUTE !', 'SALTA!', 'SKOK!', 'LOMPAT!', 'NHẢY QUA!', 'กระโดดข้าม!', 'छलाँग!', 'اقفز!', '跃过！', '躍過！', '飛び越えろ！', '뛰어넘어!'],

    'Vault and kick': ['Atla ve tekmele', 'Salto y patada', 'Salto e chute', 'Прыжок и удар ногой', 'Sprung und Tritt', 'Saut et coup de pied', 'Salto e calcio', 'Skok i kopnięcie', 'Lompat dan tendang', 'Nhảy qua và đá', 'กระโดดเตะ', 'छलाँग और लात', 'قفزة وركلة', '跃起踢击', '躍起踢擊', '飛び越え蹴り', '뛰어넘어 차기'],
    'Over the table': ['Masanın üstünden', 'Sobre la mesa', 'Por cima da mesa', 'Через стол', 'Über den Tisch', 'Par-dessus la table', 'Sopra il tavolo', 'Przez stół', 'Melompati meja', 'Vượt qua bàn', 'ข้ามโต๊ะ', 'मेज़ के ऊपर से', 'فوق الطاولة', '越过桌子', '越過桌子', '机を越えて', '탁자를 넘어'],
    'Over the stool': ['Taburenin üstünden', 'Sobre el taburete', 'Por cima do banquinho', 'Через табурет', 'Über den Hocker', 'Par-dessus le tabouret', 'Sopra lo sgabello', 'Przez taboret', 'Melompati bangku', 'Vượt qua ghế đẩu', 'ข้ามม้านั่ง', 'स्टूल के ऊपर से', 'فوق المقعد', '越过凳子', '越過凳子', '腰掛けを越えて', '의자를 넘어'],
    'Over the barrel': ['Fıçının üstünden', 'Sobre el barril', 'Por cima do barril', 'Через бочку', 'Über das Fass', 'Par-dessus le tonneau', 'Sopra il barile', 'Przez beczkę', 'Melompati tong', 'Vượt qua thùng', 'ข้ามถัง', 'पीपे के ऊपर से', 'فوق البرميل', '越过酒桶', '越過酒桶', '樽を越えて', '통을 넘어'],
    'Over the bale': ['Saman balyasının üstünden', 'Sobre la paca', 'Por cima do fardo', 'Через тюк', 'Über den Ballen', 'Par-dessus la botte', 'Sopra la balla', 'Przez belę', 'Melompati jerami', 'Vượt qua bó rơm', 'ข้ามฟาง', 'गट्ठर के ऊपर से', 'فوق حزمة القش', '越过草垛', '越過草垛', '俵を越えて', '짚단을 넘어'],
    'Table flip': ['Masa devirme', 'Volcar la mesa', 'Virar a mesa', 'Опрокинуть стол', 'Tisch umwerfen', 'Table renversée', 'Ribaltare il tavolo', 'Przewrócenie stołu', 'Balik meja', 'Lật bàn', 'พลิกโต๊ะ', 'मेज़ पलटना', 'قلب الطاولة', '掀桌', '掀桌', 'ちゃぶ台返し', '탁자 뒤집기'],
    'Round the post': ['Direğin etrafından', 'Alrededor del poste', 'Ao redor do poste', 'Вокруг столба', 'Um den Pfosten', 'Autour du poteau', 'Intorno al palo', 'Wokół słupa', 'Memutari tiang', 'Vòng quanh cột', 'อ้อมเสา', 'खंभे के चारों ओर', 'حول العمود', '绕柱', '繞柱', '柱を回って', '기둥을 돌아'],
    'Lantern cut down': ['Fener kesildi', 'Farol derribado', 'Lanterna derrubada', 'Фонарь срублен', 'Laterne gefällt', 'Lanterne tranchée', 'Lanterna abbattuta', 'Latarnia ścięta', 'Lentera ditebas', 'Chém rơi đèn lồng', 'ฟันโคมตก', 'लालटेन काटी', 'قُطع الفانوس', '斩落灯笼', '斬落燈籠', '灯籠を斬り落とす', '등롱을 베어 떨어뜨림'],
    'Off the wall': ['Duvardan sekerek', 'Desde la pared', 'Da parede', 'От стены', 'Von der Wand', 'Rebond sur le mur', 'Dal muro', 'Od ściany', 'Dari dinding', 'Bật tường', 'ถีบกำแพง', 'दीवार से', 'من الجدار', '蹬墙', '蹬牆', '壁を蹴って', '벽을 차고'],
    'From the steps': ['Basamaklardan', 'Desde los escalones', 'Dos degraus', 'Со ступеней', 'Von den Stufen', 'Depuis les marches', 'Dai gradini', 'Ze schodów', 'Dari tangga', 'Từ bậc thềm', 'จากขั้นบันได', 'सीढ़ियों से', 'من الدرجات', '从台阶上', '從台階上', '石段から', '계단에서'],
    'Blade stuck in the post!': ['Kılıç direğe saplandı!', '¡Hoja clavada en el poste!', 'Lâmina presa no poste!', 'Клинок застрял в столбе!', 'Klinge steckt im Pfosten!', 'Lame coincée dans le poteau !', 'Lama incastrata nel palo!', 'Ostrze utkwiło w słupie!', 'Pedang tertancap di tiang!', 'Lưỡi kiếm kẹt vào cột!', 'ดาบติดเสา!', 'ब्लेड खंभे में फँसा!', 'علق النصل في العمود!', '刀卡进柱子！', '刀卡進柱子！', '刃が柱に刺さった！', '칼날이 기둥에 박혔다!'],
    'Slipped on the sake!': ['Sakede kaydı!', '¡Resbaló con el sake!', 'Escorregou no saquê!', 'Поскользнулся на сакэ!', 'Auf dem Sake ausgerutscht!', 'Glissade sur le saké !', 'Scivolato sul sakè!', 'Poślizg na sake!', 'Terpeleset sake!', 'Trượt chân vì rượu sake!', 'ลื่นสาเก!', 'साके पर फिसला!', 'انزلق على الساكي!', '踩到清酒滑倒！', '踩到清酒滑倒！', '酒で滑った！', '사케에 미끄러졌다!'],
    'Slipped on the water!': ['Suda kaydı!', '¡Resbaló con el agua!', 'Escorregou na água!', 'Поскользнулся на воде!', 'Auf dem Wasser ausgerutscht!', 'Glissade sur l\'eau !', 'Scivolato sull\'acqua!', 'Poślizg na wodzie!', 'Terpeleset air!', 'Trượt chân vì nước!', 'ลื่นน้ำ!', 'पानी पर फिसला!', 'انزلق على الماء!', '踩到水滑倒！', '踩到水滑倒！', '水で滑った！', '물에 미끄러졌다!'],
    'Blocks with the stool': ['Tabureyle blok', 'Bloquea con el taburete', 'Bloqueia com o banquinho', 'Блок табуретом', 'Blockt mit dem Hocker', 'Bloque avec le tabouret', 'Para con lo sgabello', 'Blok taboretem', 'Menangkis dengan bangku', 'Đỡ bằng ghế đẩu', 'ใช้ม้านั่งกัน', 'स्टूल से ब्लॉक', 'يصد بالمقعد', '以凳子格挡', '以凳子格擋', '腰掛けで受ける', '의자로 막기'],
    'Blocks with the bucket': ['Kovayla blok', 'Bloquea con el cubo', 'Bloqueia com o balde', 'Блок ведром', 'Blockt mit dem Eimer', 'Bloque avec le seau', 'Para con il secchio', 'Blok wiadrem', 'Menangkis dengan ember', 'Đỡ bằng xô', 'ใช้ถังน้ำกัน', 'बाल्टी से ब्लॉक', 'يصد بالدلو', '以水桶格挡', '以水桶格擋', '桶で受ける', '양동이로 막기'],
    'Blocks with the jar': ['Küple blok', 'Bloquea con la vasija', 'Bloqueia com o jarro', 'Блок кувшином', 'Blockt mit dem Krug', 'Bloque avec la jarre', 'Para con la giara', 'Blok dzbanem', 'Menangkis dengan guci', 'Đỡ bằng chum', 'ใช้ไหกัน', 'मटके से ब्लॉक', 'يصد بالجرة', '以陶罐格挡', '以陶罐格擋', '壺で受ける', '항아리로 막기'],
    'Blocks with the cup': ['Fincanla blok', 'Bloquea con la taza', 'Bloqueia com a xícara', 'Блок чашкой', 'Blockt mit dem Becher', 'Bloque avec la coupe', 'Para con la tazza', 'Blok kubkiem', 'Menangkis dengan cangkir', 'Đỡ bằng chén', 'ใช้ถ้วยกัน', 'प्याले से ब्लॉक', 'يصد بالكوب', '以酒杯格挡', '以酒杯格擋', '杯で受ける', '잔으로 막기'],
    'Blocks with the bottle': ['Şişeyle blok', 'Bloquea con la botella', 'Bloqueia com a garrafa', 'Блок бутылкой', 'Blockt mit der Flasche', 'Bloque avec la bouteille', 'Para con la bottiglia', 'Blok butelką', 'Menangkis dengan botol', 'Đỡ bằng chai', 'ใช้ขวดกัน', 'बोतल से ब्लॉक', 'يصد بالزجاجة', '以酒瓶格挡', '以酒瓶格擋', '徳利で受ける', '병으로 막기'],
    'Breaks it over the head': ['Kafasında kırdı', 'Se lo rompe en la cabeza', 'Quebra na cabeça', 'Разбил о голову', 'Auf dem Kopf zerschlagen', 'Brisé sur la tête', 'Glielo rompe in testa', 'Rozbite na głowie', 'Dipecahkan di kepala', 'Đập vỡ lên đầu', 'ฟาดหัวแตก', 'सिर पर तोड़ा', 'حطمه على رأسه', '砸在头上', '砸在頭上', '頭で叩き割る', '머리에 깨뜨림'],
    'Stool swing': ['Tabure savurma', 'Golpe de taburete', 'Golpe de banquinho', 'Удар табуретом', 'Hockerschwung', 'Coup de tabouret', 'Colpo di sgabello', 'Zamach taboretem', 'Ayunan bangku', 'Vung ghế đẩu', 'เหวี่ยงม้านั่ง', 'स्टूल का वार', 'ضربة بالمقعد', '抡凳子', '掄凳子', '腰掛けを振る', '의자 휘두르기'],
    'Throws it': ['Fırlattı', 'Lo lanza', 'Arremessa', 'Бросок', 'Wirft es', 'Le lance', 'Lo lancia', 'Rzut', 'Melempar', 'Ném', 'ขว้าง', 'फेंका', 'رماه', '掷出', '擲出', '投げつける', '던지기'],
    'Kicks it at them': ['Ona doğru tekmeledi', 'Se lo lanza de una patada', 'Chuta contra ele', 'Пинком в противника', 'Tritt es auf ihn', 'Shoot vers lui', 'Glielo calcia contro', 'Kopnięte w niego', 'Ditendang ke arahnya', 'Đá vào đối thủ', 'เตะใส่', 'उस पर लात मारी', 'ركله نحوه', '踢向对手', '踢向對手', '蹴りつける', '상대에게 차기'],
    'Kicked through the table': ['Masanın içinden tekmelendi', 'Pateado a través de la mesa', 'Chutado através da mesa', 'Пинком сквозь стол', 'Durch den Tisch getreten', 'Envoyé à travers la table', 'Calciato attraverso il tavolo', 'Kopnięty przez stół', 'Ditendang menembus meja', 'Bị đá xuyên qua bàn', 'ถูกเตะทะลุโต๊ะ', 'मेज़ के आर-पार लात', 'رُكل عبر الطاولة', '被踢穿桌子', '被踢穿桌子', '机ごと蹴り飛ばす', '탁자를 뚫고 걷어참'],
    'Kicked over the stool': ['Taburenin üstüne tekmelendi', 'Pateado sobre el taburete', 'Chutado sobre o banquinho', 'Пинком через табурет', 'Über den Hocker getreten', 'Envoyé par-dessus le tabouret', 'Calciato sopra lo sgabello', 'Kopnięty na taboret', 'Ditendang ke bangku', 'Bị đá qua ghế đẩu', 'ถูกเตะข้ามม้านั่ง', 'स्टूल पर लात', 'رُكل فوق المقعد', '被踢过凳子', '被踢過凳子', '腰掛けへ蹴り飛ばす', '의자 너머로 걷어참'],
    'Kicked into the crate': ['Sandığa tekmelendi', 'Pateado contra la caja', 'Chutado na caixa', 'Пинком в ящик', 'In die Kiste getreten', 'Envoyé dans la caisse', 'Calciato nella cassa', 'Kopnięty w skrzynię', 'Ditendang ke peti', 'Bị đá vào thùng gỗ', 'ถูกเตะใส่ลัง', 'संदूक में लात', 'رُكل نحو الصندوق', '被踢进木箱', '被踢進木箱', '木箱へ蹴り飛ばす', '상자로 걷어참'],
    'Kicked into the barrel': ['Fıçıya tekmelendi', 'Pateado contra el barril', 'Chutado no barril', 'Пинком в бочку', 'In das Fass getreten', 'Envoyé dans le tonneau', 'Calciato nel barile', 'Kopnięty w beczkę', 'Ditendang ke tong', 'Bị đá vào thùng', 'ถูกเตะใส่ถัง', 'पीपे में लात', 'رُكل نحو البرميل', '被踢进酒桶', '被踢進酒桶', '樽へ蹴り飛ばす', '통으로 걷어참'],
    'Kicked into the straw': ['Samanlara tekmelendi', 'Pateado contra la paja', 'Chutado na palha', 'Пинком в солому', 'Ins Stroh getreten', 'Envoyé dans la paille', 'Calciato nella paglia', 'Kopnięty w słomę', 'Ditendang ke jerami', 'Bị đá vào đống rơm', 'ถูกเตะใส่กองฟาง', 'पुआल में लात', 'رُكل نحو القش', '被踢进草垛', '被踢進草垛', '俵へ蹴り飛ばす', '짚더미로 걷어참'],
    'Kicked into the jar': ['Küpe tekmelendi', 'Pateado contra la vasija', 'Chutado no jarro', 'Пинком в кувшин', 'In den Krug getreten', 'Envoyé dans la jarre', 'Calciato nella giara', 'Kopnięty w dzban', 'Ditendang ke guci', 'Bị đá vào chum', 'ถูกเตะใส่ไห', 'मटके में लात', 'رُكل نحو الجرة', '被踢进陶罐', '被踢進陶罐', '壺へ蹴り飛ばす', '항아리로 걷어참'],
    'Kicked over the bucket': ['Kovanın üstüne tekmelendi', 'Pateado sobre el cubo', 'Chutado sobre o balde', 'Пинком через ведро', 'Über den Eimer getreten', 'Envoyé par-dessus le seau', 'Calciato sopra il secchio', 'Kopnięty na wiadro', 'Ditendang ke ember', 'Bị đá qua xô', 'ถูกเตะข้ามถังน้ำ', 'बाल्टी पर लात', 'رُكل فوق الدلو', '被踢过水桶', '被踢過水桶', '桶へ蹴り飛ばす', '양동이 너머로 걷어참'],
    'Spare sword from the rack': ['Raftan yedek kılıç', 'Espada de repuesto del soporte', 'Espada reserva do suporte', 'Запасной меч со стойки', 'Ersatzschwert vom Ständer', 'Épée de rechange du râtelier', 'Spada di riserva dalla rastrelliera', 'Zapasowy miecz ze stojaka', 'Pedang cadangan dari rak', 'Kiếm dự phòng trên giá', 'ดาบสำรองจากชั้นวาง', 'रैक से अतिरिक्त तलवार', 'سيف احتياطي من الحامل', '从刀架取备用刀', '從刀架取備用刀', '刀掛けから予備の刀', '거치대의 예비 검'],

    'Block or parry, then strike back at once!': ['Blokla ya da savuştur, sonra hemen karşılık ver!', '¡Bloquea o desvía y contraataca al instante!', 'Bloqueie ou apare e contra-ataque na hora!', 'Блок или парирование — и сразу контратака!', 'Blocken oder parieren, dann sofort kontern!', 'Bloque ou pare, puis contre-attaque aussitôt !', 'Para o devia, poi contrattacca subito!', 'Zablokuj lub sparuj, a potem od razu kontratakuj!', 'Tangkis atau tepis, lalu langsung serang balik!', 'Đỡ hoặc gạt, rồi phản đòn ngay!', 'ป้องกันหรือปัดดาบ แล้วสวนกลับทันที!', 'ब्लॉक या पैरी करो, फिर तुरंत पलटवार!', 'صُدّ أو اصرف الضربة، ثم ردّ فورًا!', '格挡或招架，然后立刻反击！', '格擋或招架，然後立刻反擊！', '防いだら、すぐに反撃！', '막거나 쳐내고, 바로 반격!'],
    'Defend more for a stronger counter: 一 二 三': ['Daha çok savun, karşılık daha güçlü olsun: 一 二 三', 'Defiende más para un contraataque más fuerte: 一 二 三', 'Defenda mais para um contra-ataque mais forte: 一 二 三', 'Больше защит — сильнее контратака: 一 二 三', 'Mehr Abwehr, stärkerer Konter: 一 二 三', 'Défends plus pour une contre-attaque plus forte : 一 二 三', 'Difendi di più per un contrattacco più forte: 一 二 三', 'Więcej obron – silniejsza kontra: 一 二 三', 'Bertahan lebih banyak, serangan balik lebih kuat: 一 二 三', 'Phòng thủ nhiều hơn, phản đòn mạnh hơn: 一 二 三', 'ป้องกันมากขึ้น สวนกลับแรงขึ้น: 一 二 三', 'ज़्यादा बचाव, ज़्यादा ताक़तवर पलटवार: 一 二 三', 'دافع أكثر لردّ أقوى: 一 二 三', '防得越多，反击越强：一 二 三', '防得越多，反擊越強：一 二 三', '守るほど反撃が強くなる：一 二 三', '더 많이 막을수록 더 강한 반격: 一 二 三'],

    'Something to use is in reach: tap this button.': ['Kullanabileceğin bir şey yakında: bu düğmeye dokun.', 'Hay algo a mano para usar: toca este botón.', 'Há algo para usar por perto: toque neste botão.', 'Рядом есть что использовать: нажми эту кнопку.', 'Etwas Nützliches in Reichweite: tippe auf diese Taste.', 'Un objet est à portée : touche ce bouton.', 'C\'è qualcosa da usare a portata: tocca questo pulsante.', 'Coś do użycia jest w zasięgu: dotknij tego przycisku.', 'Ada yang bisa dipakai di dekatmu: ketuk tombol ini.', 'Có thứ để dùng ở gần: chạm nút này.', 'มีของให้ใช้อยู่ใกล้ ๆ: แตะปุ่มนี้', 'पास में कुछ इस्तेमाल करने लायक है: यह बटन दबाओ।', 'هناك شيء يمكن استخدامه قريبًا: المس هذا الزر.', '附近有可利用的东西：点这个按钮。', '附近有可利用的東西：點這個按鈕。', '使える物が近くにある：このボタンを押そう。', '쓸 수 있는 물건이 근처에 있다: 이 버튼을 눌러.'],
    'Use it': ['Kullan', 'Usar', 'Usar', 'Использовать', 'Benutzen', 'Utiliser', 'Usa', 'Użyj', 'Pakai', 'Dùng', 'ใช้', 'इस्तेमाल करो', 'استخدم', '使用', '使用', '使う', '사용'],
  };
  const D = ND.duel || (ND.duel = {});
  const IDX = {}; LANGS.forEach((l, i) => { IDX[l] = i; });
  D.TR = T; D.TR_LANGS = LANGS;
  D.tr = (s) => {
    if (typeof s !== 'string') return s;
    const lang = ND.i18n && ND.i18n.lang, i = IDX[lang];
    if (i == null) return s;
    const row = T[s];
    if (row) return row[i] || s;
    return s;
  };
})(window.ND);
