// Journey copy is independent of the legacy endings, which remain available to existing saves.
(function (ND) {
  'use strict';
  const keys = ['route', 'rival', 'optional', 'win', 'earned', 'missed', 'mastery', 'reward', 'classic', 'legacy', 'colors', 'locked', 'old', 'shura', 'duel', 'clear', 'stage'];
  const goalKeys = ['parry', 'counter', 'heavy', 'kick', 'air', 'dash', 'combo', 'ranged', 'special', 'break'];
  const ids = Object.keys(ND.JOURNEY.routes);
  const copy = {
    en: {
      ui: ['Character journey', 'Final rival', 'Optional mastery', 'Win this fight to keep the star.', 'Mastery star earned', 'Star not earned · Try on a replay', 'Mastery stars', 'Complete the journey with 6 of 8 stars to earn your title and Legacy colors. Stars carry over between replays.', 'Original colors', 'Legacy colors', 'Appearance', 'Earn 6 mastery stars and finish this character’s journey.', 'Your previous journey and rewards are preserved. Replay to explore the new route.', 'Shura challenge: complete 3 different character journeys.', 'Win this duel to unlock', 'Journey complete', 'Chapter'],
      goals: ['Parries', 'Counter hits', 'Heavy hits', 'Kick hits', 'Air hits', 'Dash attack hits', 'Third combo hits', 'Projectile hits', 'Ki technique hits', 'Guard breaks'],
      titles: ['Crimson Oath', 'Unbound Wind', 'Mountain Heart', 'Winter Footsteps', 'Moonlit Blossom', 'Unbroken Banner', 'Unmasked Courage', 'Silent Promise', 'Unchained Tiger', 'Open Hand', 'Still Breeze', 'Far Horizon', 'A Second Dawn'],
      endings: ['Akane lowers her blade before Ren. Her school will be rebuilt through teaching, not revenge.', 'Aoi finishes the old duel with Akane and leaves the temple as an equal, free to choose his own path.', 'Kuro and Tetsu lay down their weapons. The mountain road is open to the villagers again.', 'Yuki accepts Hana’s offered hand. For the first time, she leaves footprints beside someone else’s.', 'Hana brings Yuki back to the lantern festival. Her final dance has room for a friend.', 'Tetsu wins Kuro’s respect and plants his banner at the pass: no villager will be turned away.', 'Ren breaks through Kage’s tricks and removes his own mask. He no longer needs fear to be heard.', 'Kage lets Ren see his face, then disappears. This time his promise survives his shadow.', 'Tora sets his chain beside Jin’s staff. The river crossing belongs to no master.', 'Jin stops Tora without taking his life. At the waterfall, a new student asks for his first lesson.', 'Mai catches Tsubame’s last arrow in her fan. Their contest ends with a bow, not a grudge.', 'Tsubame finally reads Mai’s wind. She leaves her last arrow unloosed and turns toward a new horizon.', 'Shura faces Akane without his crown. Defeat no longer defines him; the next lesson begins at dawn.'],
    },
    tr: {
      ui: ['Karakter yolculuğu', 'Son rakip', 'İsteğe bağlı ustalık', 'Yıldızı almak için bu dövüşü kazan.', 'Ustalık yıldızı kazanıldı', 'Yıldız alınmadı · Yeniden oynarken dene', 'Ustalık yıldızları', 'Yolculuğu 8 yıldızdan 6’sıyla bitir; unvanını ve Miras renklerini kazan. Yıldızlar tekrarlar arasında korunur.', 'Asıl renkler', 'Miras renkleri', 'Görünüm', '6 ustalık yıldızı kazan ve bu karakterin yolculuğunu bitir.', 'Önceki yolculuğun ve ödüllerin korundu. Yeni yolu keşfetmek için yeniden oyna.', 'Shura düellosu: 3 farklı karakterin yolculuğunu tamamla.', 'Bu düelloyu kazanarak aç', 'Yolculuk tamamlandı', 'Bölüm'],
      goals: ['Savuşturma', 'İsabetli karşı vuruş', 'İsabetli ağır vuruş', 'İsabetli tekme', 'Havadan isabet', 'Atılma saldırısı isabeti', 'Üçüncü kombo vuruşu', 'Mermi isabeti', 'Ki tekniği isabeti', 'Gard kırma'],
      titles: ['Kızıl Yemin', 'Özgür Rüzgâr', 'Dağın Yüreği', 'Kışın Ayak İzleri', 'Ay Çiçeği', 'Yıkılmayan Sancak', 'Maskesiz Cesaret', 'Sessiz Söz', 'Zincirsiz Kaplan', 'Açık El', 'Dingin Esinti', 'Uzak Ufuk', 'İkinci Şafak'],
      endings: ['Akane, Ren’in önünde kılıcını indirir. Okulunu intikamla değil, öğreterek yeniden kuracaktır.', 'Aoi, Akane ile yarım kalan düellosunu bitirir. Tapınaktan kendi yolunu seçebilen bir eşit olarak ayrılır.', 'Kuro ve Tetsu silahlarını indirir. Dağ yolu yeniden köylülere açılır.', 'Yuki, Hana’nın uzattığı eli tutar. İlk kez karda bir başkasının yanında iz bırakır.', 'Hana, Yuki’yi fener şenliğine götürür. Son dansında bir dosta da yer vardır.', 'Tetsu, Kuro’nun saygısını kazanır ve geçide sancağını diker: artık hiçbir köylü geri çevrilmeyecektir.', 'Ren, Kage’nin oyunlarını aşar ve kendi maskesini çıkarır. Sesini duyurmak için korkuya ihtiyacı yoktur.', 'Kage, Ren’e yüzünü gösterip kaybolur. Bu kez verdiği söz gölgesinden uzun yaşar.', 'Tora zincirini Jin’in asasının yanına bırakır. Nehir geçidi artık hiçbir efendiye ait değildir.', 'Jin, Tora’yı öldürmeden durdurur. Şelalede yeni bir öğrenci ilk dersini ister.', 'Mai, Tsubame’nin son okunu yelpazesiyle yakalar. Yarışmaları kinle değil, bir selamla biter.', 'Tsubame sonunda Mai’nin rüzgârını okur. Son okunu atmadan yeni bir ufka yönelir.', 'Shura, Akane’nin karşısına tacı olmadan çıkar. Onu artık yenilgi tanımlamaz; yeni dersi şafakta başlar.'],
    },
    de: {
      ui: ['Charakterreise', 'Letzter Rivale', 'Optionale Meisterschaft', 'Gewinne diesen Kampf, um den Stern zu behalten.', 'Meisterstern verdient', 'Kein Stern · Versuche es beim Wiederholen', 'Meistersterne', 'Beende die Reise mit 6 von 8 Sternen für deinen Titel und die Vermächtnisfarben. Sterne bleiben bei Wiederholungen erhalten.', 'Originalfarben', 'Vermächtnisfarben', 'Aussehen', 'Verdiene 6 Meistersterne und beende die Reise dieses Charakters.', 'Deine frühere Reise und Belohnungen bleiben erhalten. Spiele erneut, um den neuen Weg zu entdecken.', 'Shura-Duell: Beende 3 verschiedene Charakterreisen.', 'Gewinne dieses Duell und schalte frei', 'Reise abgeschlossen', 'Kapitel'],
      goals: ['Paraden', 'Kontertreffer', 'Schwere Treffer', 'Tritt-Treffer', 'Lufttreffer', 'Sprintangriff-Treffer', 'Dritte Kombotreffer', 'Projektiltreffer', 'Ki-Technik-Treffer', 'Deckungsbrüche'],
      titles: ['Roter Schwur', 'Freier Wind', 'Herz des Berges', 'Winterspuren', 'Mondblüte', 'Ungebrochenes Banner', 'Mut ohne Maske', 'Stilles Versprechen', 'Tiger ohne Ketten', 'Offene Hand', 'Stille Brise', 'Ferner Horizont', 'Zweite Morgenröte'],
      endings: ['Akane senkt die Klinge vor Ren. Sie wird ihre Schule durch Unterricht statt Rache erneuern.', 'Aoi beendet sein altes Duell mit Akane und verlässt den Tempel als ebenbürtiger Krieger.', 'Kuro und Tetsu legen die Waffen nieder. Der Bergweg steht den Dorfbewohnern wieder offen.', 'Yuki nimmt Hanas Hand. Zum ersten Mal hinterlässt sie Spuren neben einem anderen Menschen.', 'Hana bringt Yuki zum Laternenfest. Ihr letzter Tanz bietet Platz für eine Freundin.', 'Tetsu gewinnt Kuros Respekt. Unter seinem Banner bleibt der Pass für die Dorfbewohner offen.', 'Ren durchschaut Kages Täuschungen und nimmt seine Maske ab. Er braucht keine Angst mehr.', 'Kage zeigt Ren sein Gesicht und verschwindet. Sein Versprechen bleibt bestehen.', 'Tora legt seine Kette neben Jins Stab. Der Flussübergang gehört keinem Herrn.', 'Jin hält Tora auf, ohne ihn zu töten. Am Wasserfall beginnt die erste Lektion eines neuen Schülers.', 'Mai fängt Tsubames letzten Pfeil mit dem Fächer. Ihr Wettstreit endet mit einer Verbeugung.', 'Tsubame versteht Mais Wind. Sie lässt den letzten Pfeil ruhen und sucht einen neuen Horizont.', 'Shura tritt Akane ohne Krone gegenüber. Bei Tagesanbruch beginnt seine nächste Lektion.'],
    },
    fr: {
      ui: ['Parcours du personnage', 'Rival final', 'Maîtrise facultative', 'Gagne ce combat pour conserver l’étoile.', 'Étoile de maîtrise obtenue', 'Étoile manquée · Réessaie au prochain parcours', 'Étoiles de maîtrise', 'Termine le parcours avec 6 étoiles sur 8 pour gagner ton titre et les couleurs Héritage. Les étoiles sont conservées entre les parcours.', 'Couleurs originales', 'Couleurs Héritage', 'Apparence', 'Gagne 6 étoiles de maîtrise et termine le parcours de ce personnage.', 'Ton ancien parcours et ses récompenses sont conservés. Rejoue pour découvrir le nouveau chemin.', 'Duel de Shura : termine les parcours de 3 personnages différents.', 'Gagne ce duel pour débloquer', 'Parcours terminé', 'Chapitre'],
      goals: ['Parades', 'Contres réussis', 'Coups lourds réussis', 'Coups de pied réussis', 'Coups aériens réussis', 'Attaques en ruée réussies', 'Troisièmes coups de combo', 'Projectiles au but', 'Techniques ki au but', 'Gardes brisées'],
      titles: ['Serment écarlate', 'Vent libre', 'Cœur de montagne', 'Traces hivernales', 'Fleur de lune', 'Bannière invaincue', 'Courage sans masque', 'Promesse silencieuse', 'Tigre sans chaînes', 'Main ouverte', 'Brise paisible', 'Horizon lointain', 'Seconde aube'],
      endings: ['Akane baisse sa lame devant Ren. Elle rebâtira son école par l’enseignement, pas la vengeance.', 'Aoi achève son ancien duel avec Akane et quitte le temple libre de choisir sa voie.', 'Kuro et Tetsu déposent leurs armes. Les villageois peuvent à nouveau franchir la montagne.', 'Yuki prend la main de Hana. Pour la première fois, ses pas accompagnent ceux d’une amie.', 'Hana ramène Yuki à la fête des lanternes. Sa dernière danse accueille une amie.', 'Tetsu gagne le respect de Kuro et plante sa bannière au col. Les villageois peuvent passer.', 'Ren déjoue Kage et retire son masque. Il n’a plus besoin de faire peur pour être entendu.', 'Kage montre son visage à Ren, puis disparaît. Sa promesse demeure.', 'Tora pose sa chaîne près du bâton de Jin. Le passage de la rivière n’appartient plus à aucun maître.', 'Jin arrête Tora sans le tuer. Près de la cascade, un nouvel élève demande sa première leçon.', 'Mai attrape la dernière flèche de Tsubame dans son éventail. Leur défi se termine par un salut.', 'Tsubame comprend enfin le vent de Mai. Elle garde sa dernière flèche et cherche un nouvel horizon.', 'Shura affronte Akane sans sa couronne. À l’aube commence sa prochaine leçon.'],
    },
    es: {
      ui: ['Viaje del personaje', 'Rival final', 'Maestría opcional', 'Gana este combate para conservar la estrella.', 'Estrella de maestría obtenida', 'Sin estrella · Inténtalo al repetir', 'Estrellas de maestría', 'Termina el viaje con 6 de 8 estrellas para ganar tu título y los colores Legado. Las estrellas se conservan al repetir.', 'Colores originales', 'Colores Legado', 'Aspecto', 'Consigue 6 estrellas de maestría y termina el viaje de este personaje.', 'Tu viaje anterior y sus premios se conservan. Repite para descubrir la nueva ruta.', 'Duelo de Shura: termina los viajes de 3 personajes diferentes.', 'Gana este duelo para desbloquear', 'Viaje completado', 'Capítulo'],
      goals: ['Desvíos', 'Contraataques acertados', 'Golpes fuertes acertados', 'Patadas acertadas', 'Golpes aéreos acertados', 'Ataques en carrera acertados', 'Terceros golpes de combo', 'Proyectiles acertados', 'Técnicas ki acertadas', 'Guardias rotas'],
      titles: ['Juramento carmesí', 'Viento libre', 'Corazón de montaña', 'Huellas de invierno', 'Flor lunar', 'Estandarte intacto', 'Valor sin máscara', 'Promesa silenciosa', 'Tigre sin cadenas', 'Mano abierta', 'Brisa serena', 'Horizonte lejano', 'Segundo amanecer'],
      endings: ['Akane baja su espada ante Ren. Reconstruirá su escuela enseñando, sin buscar venganza.', 'Aoi termina su antiguo duelo con Akane y deja el templo libre para elegir su camino.', 'Kuro y Tetsu deponen las armas. El camino de montaña vuelve a abrirse a los aldeanos.', 'Yuki acepta la mano de Hana. Por primera vez, deja huellas junto a otra persona.', 'Hana lleva a Yuki al festival de faroles. Su último baile tiene sitio para una amiga.', 'Tetsu gana el respeto de Kuro y planta su estandarte en el paso. Ningún aldeano será rechazado.', 'Ren supera los engaños de Kage y se quita la máscara. Ya no necesita inspirar miedo.', 'Kage muestra su rostro a Ren y desaparece. Su promesa permanece.', 'Tora deja su cadena junto al bastón de Jin. El paso del río ya no tiene dueño.', 'Jin detiene a Tora sin matarlo. En la cascada, un nuevo alumno pide su primera lección.', 'Mai atrapa la última flecha de Tsubame con su abanico. Su desafío termina con una reverencia.', 'Tsubame comprende el viento de Mai. Guarda la última flecha y busca un nuevo horizonte.', 'Shura se enfrenta a Akane sin su corona. Su próxima lección comienza al amanecer.'],
    },
    pt: {
      ui: ['Jornada do personagem', 'Rival final', 'Maestria opcional', 'Vença esta luta para guardar a estrela.', 'Estrela de maestria conquistada', 'Sem estrela · Tente ao jogar novamente', 'Estrelas de maestria', 'Termine a jornada com 6 de 8 estrelas para ganhar seu título e as cores Legado. As estrelas são mantidas ao repetir.', 'Cores originais', 'Cores Legado', 'Aparência', 'Ganhe 6 estrelas de maestria e termine a jornada deste personagem.', 'Sua jornada anterior e as recompensas foram mantidas. Jogue novamente para descobrir a nova rota.', 'Duelo de Shura: termine jornadas com 3 personagens diferentes.', 'Vença este duelo para desbloquear', 'Jornada concluída', 'Capítulo'],
      goals: ['Aparos', 'Contra-ataques acertados', 'Golpes fortes acertados', 'Chutes acertados', 'Golpes aéreos acertados', 'Ataques de avanço acertados', 'Terceiros golpes de combo', 'Projéteis acertados', 'Técnicas ki acertadas', 'Guardas quebradas'],
      titles: ['Juramento carmesim', 'Vento livre', 'Coração da montanha', 'Pegadas de inverno', 'Flor lunar', 'Estandarte intacto', 'Coragem sem máscara', 'Promessa silenciosa', 'Tigre sem correntes', 'Mão aberta', 'Brisa serena', 'Horizonte distante', 'Segundo amanhecer'],
      endings: ['Akane baixa a espada diante de Ren. Ela reconstruirá sua escola ensinando, sem buscar vingança.', 'Aoi termina seu antigo duelo com Akane e deixa o templo livre para escolher seu caminho.', 'Kuro e Tetsu baixam as armas. A estrada da montanha volta a receber os moradores.', 'Yuki aceita a mão de Hana. Pela primeira vez, deixa pegadas ao lado de outra pessoa.', 'Hana leva Yuki ao festival das lanternas. Sua última dança tem espaço para uma amiga.', 'Tetsu conquista o respeito de Kuro e ergue seu estandarte na passagem. Ninguém será barrado.', 'Ren supera os truques de Kage e tira a própria máscara. Ele não precisa mais causar medo.', 'Kage mostra seu rosto a Ren e desaparece. Sua promessa permanece.', 'Tora deixa a corrente ao lado do bastão de Jin. A travessia do rio não tem mais dono.', 'Jin detém Tora sem matá-lo. Na cachoeira, um novo aluno pede a primeira lição.', 'Mai prende a última flecha de Tsubame no leque. A disputa termina com uma reverência.', 'Tsubame entende o vento de Mai. Guarda sua última flecha e busca um novo horizonte.', 'Shura enfrenta Akane sem a coroa. Sua próxima lição começa ao amanhecer.'],
    },
    ru: {
      ui: ['Путь персонажа', 'Последний соперник', 'Необязательное мастерство', 'Выиграй бой, чтобы сохранить звезду.', 'Звезда мастерства получена', 'Без звезды · Попробуй при повторном прохождении', 'Звёзды мастерства', 'Заверши путь с 6 звёздами из 8, чтобы получить титул и цвета «Наследие». Звёзды сохраняются между прохождениями.', 'Исходные цвета', 'Цвета «Наследие»', 'Облик', 'Получи 6 звёзд мастерства и заверши путь этого персонажа.', 'Прежний путь и награды сохранены. Пройди заново, чтобы открыть новый маршрут.', 'Дуэль с Шурой: заверши пути 3 разных персонажей.', 'Выиграй эту дуэль, чтобы открыть', 'Путь завершён', 'Глава'],
      goals: ['Парирования', 'Попадания контратакой', 'Тяжёлые попадания', 'Попадания ногой', 'Попадания в воздухе', 'Попадания атакой в рывке', 'Третьи удары комбо', 'Попадания снарядом', 'Попадания техникой ки', 'Пробития защиты'],
      titles: ['Алая клятва', 'Свободный ветер', 'Сердце горы', 'Зимние следы', 'Лунный цветок', 'Несломленное знамя', 'Смелость без маски', 'Тихое обещание', 'Тигр без цепей', 'Открытая ладонь', 'Тихий бриз', 'Дальний горизонт', 'Второй рассвет'],
      endings: ['Аканэ опускает клинок перед Рэном. Она восстановит школу обучением, а не местью.', 'Аои завершает давнюю дуэль с Аканэ и покидает храм, свободный выбирать свой путь.', 'Куро и Тэцу складывают оружие. Горная дорога снова открыта для жителей.', 'Юки принимает руку Ханы. Впервые её следы идут рядом с чужими.', 'Хана приводит Юки на праздник фонарей. В последнем танце есть место для подруги.', 'Тэцу завоёвывает уважение Куро и поднимает знамя на перевале. Никому из жителей не откажут в проходе.', 'Рэн раскрывает уловки Кагэ и снимает маску. Ему больше не нужен страх, чтобы быть услышанным.', 'Кагэ показывает Рэну лицо и исчезает. Его обещание остаётся.', 'Тора кладёт цепь рядом с посохом Дзина. У речной переправы больше нет хозяина.', 'Дзин останавливает Тору, не убивая его. У водопада новый ученик просит первый урок.', 'Май ловит веером последнюю стрелу Цубамэ. Их состязание заканчивается поклоном.', 'Цубамэ понимает ветер Май. Она сохраняет последнюю стрелу и идёт к новому горизонту.', 'Шура выходит к Аканэ без короны. На рассвете начинается его следующий урок.'],
    },
  };
  const catalogs = {};
  for (const [lang, c] of Object.entries(copy)) {
    const out = catalogs[lang] = Object.fromEntries(keys.map((k, i) => [k, c.ui[i]]));
    out.goals = Object.fromEntries(goalKeys.map((k, i) => [k, c.goals[i]]));
    out.titles = Object.fromEntries(ids.map((k, i) => [k, c.titles[i]]));
    out.endings = Object.fromEntries(ids.map((k, i) => [k, c.endings[i]]));
  }
  ND.JOURNEY.catalogs = catalogs;
  ND.JOURNEY.text = () => catalogs[ND.i18n ? ND.i18n.lang : 'en'] || catalogs.en;
})(window.ND);
